spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.OracleDriver
    username: System
    password: welcome123
  jpa:
    hibernate:
      ddl-auto: create

#spring:
#  application:
#    name: course-catalog-service
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true
#  h2:
#    console:
#      enabled: true